name = "KiteViewers"
uuid = "2e593061-95e7-45e4-95f4-df0491f2e601"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.3.3"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
GLMakie = "~0.9"
PrecompileTools = "1.2"
julia = "1.9, 1.10"
